TaskManagmentSystem/TaskMangmentSYS/Controllers/ManegmentController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics.SymbolStore;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using Microsoft.AspNet.Identity.Owin;
using Newtonsoft.Json;
using Shared;
using TaskMangmentSYS.Models;

namespace TaskMangmentSYS.Controllers
{
    [Authorize]
    public class ManegmentController : BaseController
    {
        /// <summary>
        /// The Dashboard page that contains the task search criteria allow the user to do the selection of period from-to 
        /// </summary>
        /// <returns></returns>
        [Authorize]
        public ActionResult Index()
        {
            return View();
        }
        /// <summary>
        /// it will be called from the dashboard JS page . to pass the parameter StartTime , EndTime .
        /// it will do the search of getting all the result that match the search criteria .
        /// at least startTime or EndTime has to be not null 
        /// 
        /// </summary>
        /// <param name="StartTime"></param>
        /// <param name="EndTime"></param>
        /// <returns> partial view contains the list of tasks </returns>
        public ActionResult Search(DateTime? StartTime=null, DateTime? EndTime=null)
        {
            if (ModelState.IsValid)
            {
                SearchTasksModel searchList = new SearchTasksModel();

                searchList.Tasks = GetTaskRepo().GetTaskByDate(StartTime,EndTime);
                return PartialView("_SearchResult", searchList);
            }
            return Json("error");
        }

        public ActionResult ErroResult()
        {
            return View();
        }


      


      
    }
}

TaskManagmentSystem/TaskMangmentSYS/Controllers/TaskController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity.Owin;
using Shared;
using TaskMangmentSYS.Models;

namespace TaskMangmentSYS.Controllers
{
    public class TaskController : BaseController
    {
        // GET: Task
       /// <summary>
       /// called the TaskRepo to get the task by ID and show it in the page .
       /// </summary>
       /// <param name="id"></param>
       /// <returns></returns>
        [Authorize]
        public ActionResult ViewTask(int id)
        {

            TaskCommentModel model = new TaskCommentModel();
            model.Tasks = GetTaskRepo().GetById(id);
            ViewData["AllComments"] = GetCommentRepo().GetAllCommentsByTask(id);
            ViewData["CommentType"] = GetCommentRepo().GetCommentTypes();
            model.Comments = new Comments();
            return View(model);
        }

        /// <summary>
        ///view page add Task  .
        /// </summary>
        /// <returns></returns>
        [Authorize]
        public ActionResult AddTask()
        {
            ViewData["types"] = GetTaskRepo().GeTasksTypes();
            ViewData["status"] = GetTaskRepo().GetStatuses();

            ViewBag.users = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>().Users.Select(a => a.UserName).ToList();
            return View();
        }

        /// <summary>
        /// called the TaskRepo to add the task after form has been submited  .
        /// </summary>
        /// <param name="model"></param>
        /// <returns>redirect to page view task </returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult AddTask(TaskCommentModel model)
        {
            if (ModelState.IsValid)
            {
                int result = GetTaskRepo().Add(model.Tasks);
                return RedirectToAction("ViewTask", new { id = result });

            }

            return View(model);
        }
    }
}

TaskManagmentSystem/TaskMangmentSYS/Views/Manegment/ErroResult.cshtml
@{
    ViewBag.Title = "error";
    Layout = "~/Views/Shared/_MyLayout.cshtml";
}


<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Error </title>
    <script type="text/javascript" src="https://code.jquery.com/jquery-1.7.1.min.js"></script>
    <link href='https://fonts.googleapis.com/css?family=Nunito:400,300' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="~/Content/ViewComments.css">
    <link rel="stylesheet" href="~/Content/addTask.css">
</head>
<fieldset>
    <legend><span class="number">1</span> Error !</legend>

   

</fieldset>

TaskManagmentSystem/TaskMangmentSYS/Views/Manegment/Index.cshtml
@model TaskMangmentSYS.Models.SearchTasksModel
@{
    Layout = "~/Views/Shared/_MyLayout.cshtml";

}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard </title>
    <script type="text/javascript" src="https://code.jquery.com/jquery-1.7.1.min.js"></script>
    <link href='https://fonts.googleapis.com/css?family=Nunito:400,300' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="~/Content/ViewComments.css">
    <link rel="stylesheet" href="~/Content/addTask.css">
</head>


@using (Html.BeginForm())

{
 
<h1>Dashboard</h1>
   
    <fieldset>
        <legend><span class="number">1</span> Search Info</legend>

        <label for="job" class="labelTask">Date From</label>
        @Html.EditorFor(model => model.StartTime, new { id = "name", name = "user_name" })
       
        <label for="name" class="labelTask">Date To</label>
        @Html.EditorFor(model => model.EndTime, new { id = "name", name = "user_name" })

        <div>
            <button type="submit">Search</button>
        </div>

    </fieldset>


}
<div id="searchResults">
</div>
<script>

    var url = '@Url.Action("Search", "Manegment")';
    $('form').submit(function() {

        var form = $(this).serialize();
        $('#searchResults').load(url, form);
        return false; // prevent the default submit action
    });

</script>

TaskManagmentSystem/TaskMangmentSYS/Views/Manegment/_SearchResult.cshtml
@using Shared
@model TaskMangmentSYS.Models.SearchTasksModel
@{
    Layout = null;

}

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>View Task</title>

    <link href='https://fonts.googleapis.com/css?family=Nunito:400,300' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="~/Content/ViewComments.css">
</head>


@Html.AntiForgeryToken()
<h1>View Tasks</h1>
<table id="searchResult" class="container">
    <thead>
        <tr>
            <th><h1>CreatedDate</h1></th>
            <th><h1>AssignedTo</h1></th>
            <th><h1>Status</h1></th>
            <th><h1>Type</h1></th>
            <th><h1>RequiredByDate</h1></th>
            <th><h1>NextActionDate</h1></th>
            
            


        </tr>
    </thead>
    <tbody>
    @if (Model.Tasks != null)
    {
        foreach (var task in Model.Tasks)
        {
        <tr ondblclick="location.href = '@Url.Action("ViewTask", "Task", new{id=task.ID})'">
            <td>
                @Html.TextBoxFor(model => task.CreatedDate, "{0:dd-MM-yyyy}", new { disabled = "disabled" })
            </td>
            <td>
                @Html.TextBoxFor(model => task.AssignedTo, new { disabled = "disabled" })
            </td>
            <td>
                @Html.TextBoxFor(model => task.Status, new { disabled = "disabled" })
            </td>
            <td>
                @Html.TextBoxFor(model => task.Type, new { disabled = "disabled" })
            </td>
            <td>
                @if (task.RequiredByDate != null)
                {
                    @Html.TextBoxFor(model => task.RequiredByDate.Value, "{0:dd-MM-yyyy}", new { disabled = "disabled" })
                }
            </td>
            <td>
            @if (task.NextActionDate != null)
            {
                @Html.TextBoxFor(model => task.NextActionDate, "{0:dd-MM-yyyy}", new {disabled = "disabled"})
            }
            </td>


        </tr>

        }
    }


    </tbody>
</table>